sudo: required
services:
  - docker

before_install:
  - docker build -t karimekhalifa/docker-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true karimekhalifa/docker-react-test npm run test